import { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

export function useLanguage() {
  return useContext(LanguageContext)
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language')
    return saved || 'id'
  })

  useEffect(() => {
    localStorage.setItem('language', language)
  }, [language])

  const translations = {
    en: {
      sell: 'Sell',
      buy: 'Buy',
      fees: 'Fees',
      home: 'Home',
      sales: 'Sales',
      purchases: 'Purchases',
      expenses: 'Expenses',
      products: 'Products',
      inventory: 'Inventory',
      reports: 'Reports',
      cashBank: 'Cash & Bank',
      accounts: 'Accounts',
      fixedAssets: 'Fixed Assets',
      contacts: 'Contacts',
      payroll: 'Payroll',
      overview: 'Overview',
      invoices: 'Invoices',
      shipments: 'Shipments',
      orders: 'Orders',
      offers: 'Offers',
      addInvoice: 'Add Invoice',
      customer: 'Customer',
      number: 'Number',
      transactionDate: 'Transaction Date',
      dueDate: 'Due Date',
      term: 'Term',
      warehouse: 'Warehouse',
      reference: 'Reference',
      tag: 'Tag',
      showSalesPerson: 'Show Sales Person',
      showShippingInfo: 'Show Shipping Information',
      scanBarcode: 'Scan Barcode/SKU',
      priceIncludesTax: 'Price includes tax',
      product: 'Product',
      description: 'Description',
      quantity: 'Quantity',
      unit: 'Unit',
      discount: 'Discount',
      price: 'Price',
      tax: 'Tax',
      amount: 'Amount',
      addRow: 'Add Row',
      message: 'Message',
      attachment: 'Attachment',
      paymentConnect: 'Payment Connect',
      subTotal: 'Sub Total',
      additionalDiscount: 'Additional Discount',
      shippingCost: 'Shipping Cost',
      transactionFee: 'Transaction Fee',
      total: 'Total',
      deduction: 'Deduction',
      downPayment: 'Down Payment',
      remainingBill: 'Remaining Bill',
      save: 'Save',
      back: 'Back',
      guide: 'Guide',
      selectContact: 'Select contact',
      selectProduct: 'Select Product',
      selectTag: 'Select Tag',
      // Common UI
      filter: 'Filter',
      search: 'Search',
      print: 'Print',
      import: 'Import',
      add: 'Add',
      edit: 'Edit',
      delete: 'Delete',
      cancel: 'Cancel',
      confirm: 'Confirm',
      logout: 'Logout',
      // Purchase Invoice specific
      purchaseInvoices: 'Purchase Invoices',
      purchaseInvoice: 'Purchase Invoice',
      vendor: 'Vendor',
      proposedBy: 'Proposed by',
      unpaid: 'Unpaid',
      partiallyPaid: 'Partially Paid',
      paid: 'Paid',
      all: 'All',
      date: 'Date',
      status: 'Status',
      emptyData: 'Empty Data',
      startCreating: 'Let\'s start creating your first one!',
      // Orders
      orders: 'Orders',
      order: 'Order',
      // Breadcrumbs
      breadcrumbHome: 'Home',
      breadcrumbSales: 'Sales',
      breadcrumbPurchases: 'Purchases',
      // Status
      draft: 'Draft',
      sent: 'Sent',
      rejected: 'Rejected',
      approved: 'Approved',
      completed: 'Completed',
      partiallyOrdered: 'Partially Ordered',
      // Purchase Overview
      purchaseOverview: 'Purchase Overview',
      purchase: 'Purchase',
      paymentSent: 'Payment Sent',
      paidRatio: 'Paid Ratio',
      waitingForPayment: 'Waiting for Payment',
      overdue: 'Overdue',
      totalPurchaseThisMonth: 'Total Purchase This Month',
      productType: 'Product Type',
      category: 'Category',
      noData: 'No data',
      // Common actions
      report: 'Report',
      laporan: 'Report',
      panduan: 'Guide',
      tambah: 'Add',
      // Dashboard widgets
      cash: 'CASH',
      totalAccountBalance: 'Total Saldo Akun',
      account: 'Account',
      balance: 'Balance',
      noAccounts: 'No accounts',
      timeframe: 'Timeframe',
      daily: 'Daily',
      weekly: 'Weekly',
      monthly: 'Monthly',
      yearly: 'Yearly',
      billsToPay: 'BILLS YOU NEED TO PAY',
      waitingPayment: 'Waiting for payment',
      overdue: 'Overdue',
      bankAccount: 'BANK ACCOUNT',
      balanceInIBASA: 'Balance in IBASA',
      balanceInBank: 'Balance in bank',
      lastMonthExpenses: 'LAST MONTH EXPENSES',
      expenses: 'Expenses',
      giroAccount: 'GIRO ACCOUNT',
      dummyDataNotice: 'The data currently displayed is dummy data. Once you are ready,',
      clickHere: 'click here',
      toClearData: 'to clear data.',
      users: 'Users',
      purchaseInvoices: 'Purchase Invoices',
      purchaseShipments: 'Purchase Shipments',
      purchaseOrders: 'Purchase Orders',
      purchaseOffers: 'Purchase Offers',
      // More dashboard widgets
      cashFlow: 'CASH FLOW',
      totalCashInOut: 'TOTAL KELUAR MASUK KAS',
      profitLoss: 'PROFIT & LOSS',
      income: 'Income',
      expenses: 'Expenses',
      netProfit: 'Net Profit',
      netLoss: 'Net Loss',
      thisYear: 'this year',
      in: 'In',
      out: 'Out',
      grossProfit: 'Gross Profit',
      netProfitLabel: 'Net Profit',
      loadingDashboard: 'Loading dashboard data...',
      aiAssistant: 'AI Assistant',
    },
    id: {
      sell: 'Jual',
      buy: 'Beli',
      fees: 'Biaya',
      home: 'Beranda',
      sales: 'Penjualan',
      purchases: 'Pembelian',
      expenses: 'Biaya',
      products: 'Produk',
      inventory: 'Inventori',
      reports: 'Laporan',
      cashBank: 'Kas & Bank',
      accounts: 'Akun',
      fixedAssets: 'Aset Tetap',
      contacts: 'Kontak',
      payroll: 'Payroll',
      overview: 'Overview',
      invoices: 'Tagihan',
      shipments: 'Pengiriman',
      orders: 'Pemesanan',
      offers: 'Penawaran',
      addInvoice: 'Tambah Tagihan',
      customer: 'Pelanggan',
      number: 'Nomor',
      transactionDate: 'Tgl. Transaksi',
      dueDate: 'Tgl. Jatuh Tempo',
      term: 'Termin',
      warehouse: 'Gudang',
      reference: 'Referensi',
      tag: 'Tag',
      showSalesPerson: 'Tampilkan Sales Person',
      showShippingInfo: 'Tampilkan Informasi Pengiriman',
      scanBarcode: 'Scan Barcode/SKU',
      priceIncludesTax: 'Harga termasuk pajak',
      product: 'Produk',
      description: 'Deskripsi',
      quantity: 'Kuantitas',
      unit: 'Satuan',
      discount: 'Discount',
      price: 'Harga',
      tax: 'Pajak',
      amount: 'Jumlah',
      addRow: 'Tambah baris',
      message: 'Pesan',
      attachment: 'Attachment',
      paymentConnect: 'Payment Connect',
      subTotal: 'Sub Total',
      additionalDiscount: 'Tambahan Diskon',
      shippingCost: 'Biaya pengiriman',
      transactionFee: 'Biaya Transaksi',
      total: 'Total',
      deduction: 'Pemotongan',
      downPayment: 'Uang muka',
      remainingBill: 'Sisa Tagihan',
      save: 'Simpan',
      back: 'Kembali',
      guide: 'Panduan',
      selectContact: 'Pilih kontak',
      selectProduct: 'Pilih Produk',
      selectTag: 'Pilih Tag',
      // Common UI
      filter: 'Filter',
      search: 'Cari',
      print: 'Print',
      import: 'Import',
      add: 'Tambah',
      edit: 'Edit',
      delete: 'Hapus',
      cancel: 'Batal',
      confirm: 'Konfirmasi',
      logout: 'Keluar',
      // Purchase Invoice specific
      purchaseInvoices: 'Tagihan Pembelian',
      purchaseInvoice: 'Tagihan Pembelian',
      vendor: 'Vendor',
      proposedBy: 'Di ajukan oleh',
      unpaid: 'Belum Dibayar',
      partiallyPaid: 'Dibayar Sebagian',
      paid: 'Lunas',
      all: 'Semua',
      date: 'Tanggal',
      status: 'Status',
      emptyData: 'Data Kosong',
      startCreating: 'Yuk mulai buat pertamamu!',
      // Orders
      orders: 'Pemesanan',
      order: 'Pemesanan',
      // Breadcrumbs
      breadcrumbHome: 'Beranda',
      breadcrumbSales: 'Penjualan',
      breadcrumbPurchases: 'Pembelian',
      // Status
      draft: 'Draft',
      sent: 'Terkirim',
      rejected: 'Ditolak Pelanggan',
      approved: 'Disetujui Pelanggan',
      completed: 'Selesai',
      partiallyOrdered: 'Dipesan Sebagian',
      // Purchase Overview
      purchaseOverview: 'Overview Pembelian',
      purchase: 'PEMBELIAN',
      paymentSent: 'PEMBAYARAN PEMBELIAN DIKIRIM',
      paidRatio: 'RASIO LUNAS',
      waitingForPayment: 'MENUNGGU PEMBAYARAN PEMBELIAN',
      overdue: 'JATUH TEMPO TAGIHAN PEMBELIAN',
      totalPurchaseThisMonth: 'TOTAL PEMBELIAN BULAN INI',
      productType: 'Jenis Produk',
      category: 'Kategori',
      noData: 'Tidak ada data',
      // Common actions
      report: 'Laporan',
      laporan: 'Laporan',
      panduan: 'Panduan',
      tambah: 'Tambah',
      // Dashboard widgets
      cash: 'KAS',
      totalAccountBalance: 'Total Saldo Akun',
      account: 'Akun',
      balance: 'Saldo',
      noAccounts: 'Tidak ada akun',
      timeframe: 'Periode',
      daily: 'Harian',
      weekly: 'Mingguan',
      monthly: 'Bulanan',
      yearly: 'Tahunan',
      billsToPay: 'TAGIHAN YANG PERLU KAMU BAYAR',
      waitingPayment: 'Menunggu pembayaran',
      overdue: 'Jatuh tempo',
      bankAccount: 'BANK ACCOUNT',
      balanceInIBASA: 'Saldo di IBASA',
      balanceInBank: 'Saldo di bank',
      lastMonthExpenses: 'BIAYA BULAN LALU',
      expenses: 'Biaya',
      giroAccount: 'GIRO ACCOUNT',
      dummyDataNotice: 'Data yang tampil saat ini adalah data dummy. Setelah Anda siap,',
      clickHere: 'klik disini',
      toClearData: 'untuk mengosongkan data.',
      users: 'Users',
      purchaseInvoices: 'Tagihan Pembelian',
      purchaseShipments: 'Pengiriman Pembelian',
      purchaseOrders: 'Pesanan Pembelian',
      purchaseOffers: 'Penawaran Pembelian',
      // More dashboard widgets
      cashFlow: 'CASH FLOW',
      totalCashInOut: 'TOTAL KELUAR MASUK KAS',
      profitLoss: 'LABA RUGI',
      income: 'Pendapatan',
      expenses: 'Biaya',
      netProfit: 'Laba bersih',
      netLoss: 'Rugi bersih',
      thisYear: 'tahun ini',
      in: 'Masuk',
      out: 'Keluar',
      grossProfit: 'Laba kotor',
      netProfitLabel: 'Laba bersih',
      loadingDashboard: 'Memuat data dashboard...',
      aiAssistant: 'Asisten AI',
    }
  }

  const t = (key) => {
    return translations[language][key] || key
  }

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'id' : 'en')
  }

  const setLanguageDirect = (lang) => {
    if (lang === 'en' || lang === 'id') {
      setLanguage(lang)
    }
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, setLanguageDirect, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

